### ISSUE TITLE
Post videos for 2018-19

### ISSUE THREAD

**Issue by gjwehnes** [AbeRobotics/WebSite#12]

**Comment by joeyvanlierop** [comment]
Added videos. Can be found here: https://aberobotics.github.io/AbeRoboticsWebsite/videos_2018.html

**Comment by gjwehnes** [comment]
More videos are ready to post. They can be found at https://www.youtube.com/channel/UCoMZ9oLOFY7d9KRwseTyHeg/videos

This issue should probably remain open as it will be ongoing
