### ISSUE TITLE
Termonator

### ISSUE THREAD

**Issue by aldman123** [AbeRobotics/WebSite#2]
_The photo for Terminator is not a photo of Terminator. This is a simple case of mistaken identity and should be easy to fix._ Dylan told me to put something passive aggressive here so come on guys try harder. Dylan should also learn to be more accepting of new ideas. If you could update Dylan's software and the website that would be extremely helpful. He also has already escaped the room and Terminator's favorite color is red. Is there a limit to the amount of characters you can put in a Issue? I am quite terrible at essays so I hope you only read the first two sentences. Me and Dylan are also running out of things to complain about so I'll let you go now. Have a nice day.
-Alexander A & Dylan H
PS
Dylan just STARTED TO GIVE ME THE SILENT TREATMENT! WHAT A GUY LIKE SERIOUSLY?
PPS
I won't put any more stupidly long issues in the future. I hope that you get a good laugh out of this.

**Comment by Arfulmcdarful** [comment]
Just trying to narrow down what you are reporting as an issue here.
- We need to get a picture of the actual robot Terminator on its profile page
- Add how "he" likes the colour red and escaped the room challenge

Anything else or corrections to the current list?

**Comment by aldman123** [comment]
No that's all

**Comment by aldman123** [comment]
FYI Terminator is the robot on the front page
